import os


class Settings:
    ONFLEET_API_KEY_JUSH = os.environ['ONFLEET_API_KEY_JUSH']
    SHYFTPLAN_EMAIL = os.environ['SHYFTPLAN_EMAIL']
    SHYFTPLAN_JUSH_API_KEY = os.environ['SHYFTPLAN_JUSH_API_KEY']
    AIRTABLE_API_KEY = os.environ['AIRTABLE_API_KEY']
    AIRTABLE_APP_NAME = os.environ['AIRTABLE_APP_NAME']
    AIRTABLE_TABLE_NAME = os.environ['AIRTABLE_TABLE_NAME']
    AIRTABLE_VIEW_ACC_TO_CREATE = os.environ['AIRTABLE_VIEW_ACC_TO_CREATE']
    AIRTABLE_VIEW_REMOVED_RIDERS = os.environ['AIRTABLE_VIEW_REMOVED_RIDERS']
    AIRTABLE_VIEW_RIDERS_TO_SMS = os.environ['AIRTABLE_VIEW_RIDERS_TO_SMS']
    AIRTABLE_VIEW_SHIFTS_UPDATING = os.environ['AIRTABLE_VIEW_SHIFTS_UPDATING']
    AIRTABLE_VIEW_ALL_LEADS = os.environ['AIRTABLE_VIEW_ALL_LEADS']
    SERWER_SMS_API = os.environ['SERWER_SMS_API']